default_profile = "wagou"

[profile]
  [profile.alan]
    harnesses = ["opencode", "claude"]
    [profile.alan.harness]
      [profile.alan.harness.opencode]
        skills_dir = "~/.config/opencode/alan/skills"
      [profile.alan.harness.claude]
        skills_dir = "~/.claude/skills"

    [[profile.alan.dependencies]]
      name = "morning-digest"
      source = "alan-eu/alan-skills/alan-skills/skills/morning-digest"
      ref = "HEAD"

    [[profile.alan.dependencies]]
      name = "github-discussion"
      source = "alan-eu/alan-skills/alan-skills/skills/github-discussion"
      ref = "HEAD"

    [[profile.alan.dependencies]]
      name = "shared-credentials"
      source = "alan-eu/alan-skills/alan-skills/skills/shared-credentials"
      ref = "HEAD"

    [[profile.alan.dependencies]]
      name = "discussions-tracker"
      source = "alan-eu/alan-skills/alan-skills/skills/discussions-tracker"
      ref = "HEAD"

    [[profile.alan.dependencies]]
      name = "alan-identity"
      source = "alan-eu/alan-skills/alan-skills/skills/alan-identity"
      ref = "HEAD"

    [[profile.alan.dependencies]]
      name = "sfa"
      source = "alan-eu/alan-skills/alan-skills/skills/sfa"
      ref = "HEAD"

    [[profile.alan.dependencies]]
      name = "standup"
      source = "alan-eu/alan-skills/alan-skills/skills/standup"
      ref = "HEAD"

  [profile.wagou]
    harnesses = ["opencode"]
    [profile.wagou.harness]
      [profile.wagou.harness.opencode]
        skills_dir = "~/.config/opencode/wagou/skills"
