[default_session]
startup_command = "tmuxinator start workspace $(basename {}) path={} --append && tmux kill-window -t $(basename {}):1"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "alan-apps"
path = "~/Projects/alan/alan-apps"
startup_command = "tmuxinator start alan-apps"

[[session]]
name = "dotfiles"
path = "~/.local/share/chezmoi"
startup_command = "tmuxinator start dotfiles"
